ccflags-y += -Idrivers/media/platform/msm/camera_v2_15018
ccflags-y += -Idrivers/media/platform/msm/camera_v2_15018/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_15018/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
