#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_SYNAPTICS_OPPO) += synaptics_oppo_driver_4291.o synaptics_oppo_driver_3310.o synaptics_oppo_driver_3203.o synaptics_oppo_driver_3508.o
obj-$(CONFIG_SYNAPTICS_OPPO) += synaptics_redremote.o
#endif