#
# Makefile for the Synaptics touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_OPPO) += synaptics_oppo_driver_3508.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_OPPO) += synaptics_redremote.o
