ccflags-y += -Idrivers/media/platform/msm/camera_v2_15109
ccflags-y += -Idrivers/media/platform/msm/camera_v2_15109/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_15109/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
