obj-$(CONFIG_OPPO_CHARGER)	+= oppo_adc.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_battery.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_bms.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_charger.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_init.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_upper.o

obj-$(CONFIG_OPPO_CHARGER)	+= oppo_smb358.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_smb1357.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_bq24196.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_bq24157.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_bq24188.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_bq27541.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_bq27541_encrypt.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_bq2022a.o

obj-$(CONFIG_OPPO_CHARGER)	+= oppo_vooc.o
obj-$(CONFIG_OPPO_CHARGER)	+= oppo_vooc_stm8s.o
