ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo_51
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo_51/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo_51/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
