#gt915 touchpanel driver

obj-$(CONFIG_GT9XX_TOUCHPANEL_DRIVER_OPPO)	+= gt9xx.o
obj-$(CONFIG_GT9XX_TOUCHPANEL_DRIVER_OPPO)	+= circle_point.o
#gt915 update file
obj-$(CONFIG_GT9XX_TOUCHPANEL_UPDATE_OPPO)	+= gt9xx_update.o
#debug tool
obj-$(CONFIG_GT9XX_TOUCHPANEL_DEBUG_OPPO)	+= goodix_tool.o
