ccflags-y += -Idrivers/media/platform/msm/camera_v2_15018
ccflags-y += -Idrivers/media/platform/msm/camera_v2_15018/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_15018/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_15018/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_tof.o vl6180x_api.o vl6180x_i2c.o
