ccflags-y += -Idrivers/media/platform/msm/camera_v2_15018
ccflags-y += -Idrivers/media/platform/msm/camera_v2_15018/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_15018/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
