#
# Makefile for the touchscreen drivers.
#
 
# Each configuration option enables a list of files.


obj-$(CONFIG_GT1X_OPPO) += gt1x.o gt1x_generic.o gt1x_extents.o gt1x_update.o gt1x_tools.o circle_point.o
#endif