ccflags-y += -Idrivers/media/platform/msm/camera_v2_15109
ccflags-y += -Idrivers/media/platform/msm/camera_v2_15109/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_15109/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
